import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/providers";
import Header from "@/components/header";
import { Montserrat, Lilita_One } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const lilitaOne = Lilita_One({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
        style={
          {
            "--font-lilita-one": lilitaOne.style.fontFamily,
          } as React.CSSProperties
        }
      >
        <Providers>
          <div className="w-screen h-screen overflow-x-hidden relative">
            <Header />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
